export const INDO_REGION = [
  { id: "1", label: "Kabupaten Aceh Barat", value: "Aceh" },
  { id: "2", label: "Kabupaten Aceh Selatan", value: "Aceh" },
  { id: "3", label: "Kabupaten Aceh Singkil", value: "Aceh" },
  { id: "4", label: "Kabupaten Aceh Tamiang", value: "Aceh" },
  { id: "5", label: "Kabupaten Aceh Tengah", value: "Aceh" },
  { id: "6", label: "Kabupaten Aceh Tenggara", value: "Aceh" },
  { id: "7", label: "Kabupaten Aceh Utara", value: "Aceh" },
  { id: "8", label: "Kabupaten Agam", value: "Sumatera Barat" },
  { id: "9", label: "Kabupaten Alor", value: "Nusa Tenggara Timur" },
  { id: "10", label: "Kabupaten Ambon", value: "Maluku" },
  { id: "11", label: "Kabupaten Amurang", value: "Sulawesi Utara" },
  { id: "12", label: "Kabupaten Anambas", value: "Kepulauan Riau" },
  { id: "13", label: "Kabupaten Asahan", value: "Sumatera Utara" },
  { id: "14", label: "Kabupaten Badung", value: "Bali" },
  { id: "15", label: "Kabupaten Bangka", value: "Bangka Belitung" },
  { id: "16", label: "Kabupaten Bangkalan", value: "Jawa Timur" },
  { id: "17", label: "Kabupaten Banyuwangi", value: "Jawa Timur" },
  { id: "18", label: "Kabupaten Barito Selatan", value: "Kalimantan Tengah" },
  { id: "19", label: "Kabupaten Barito Timur", value: "Kalimantan Tengah" },
  { id: "20", label: "Kabupaten Bantaeng", value: "Sulawesi Selatan" },
  { id: "21", label: "Kabupaten Barru", value: "Sulawesi Selatan" },
  { id: "22", label: "Kabupaten Batu Bara", value: "Sumatera Utara" },
  { id: "23", label: "Kabupaten Bener Meriah", value: "Aceh" },
  { id: "24", label: "Kabupaten Biak Numfor", value: "Papua" },
  { id: "25", label: "Kabupaten Blitar", value: "Jawa Timur" },
  { id: "26", label: "Kabupaten Bolaang Mongondow", value: "Sulawesi Utara" },
  { id: "27", label: "Kabupaten Bondowoso", value: "Jawa Timur" },
  { id: "28", label: "Kabupaten Bojonegoro", value: "Jawa Timur" },
  { id: "29", label: "Kabupaten Bontang", value: "Kalimantan Timur" },
  { id: "30", label: "Kabupaten Boyolali", value: "Jawa Tengah" },
  { id: "31", label: "Kabupaten Brebes", value: "Jawa Tengah" },
  { id: "32", label: "Kabupaten Bulukumba", value: "Sulawesi Selatan" },
  { id: "33", label: "Kabupaten Bungo", value: "Jambi" },
  { id: "34", label: "Kabupaten Buton", value: "Sulawesi Tenggara" },
  { id: "35", label: "Kabupaten Ciamis", value: "Jawa Barat" },
  { id: "36", label: "Kabupaten Cianjur", value: "Jawa Barat" },
  { id: "37", label: "Kabupaten Cirebon", value: "Jawa Barat" },
  { id: "38", label: "Kabupaten Cilacap", value: "Jawa Tengah" },
  { id: "39", label: "Kabupaten Cirebon", value: "Jawa Barat" },
  { id: "40", label: "Kabupaten Curup", value: "Bengkulu" },
  { id: "41", label: "Kabupaten Deli Serdang", value: "Sumatera Utara" },
  { id: "42", label: "Kabupaten Demak", value: "Jawa Tengah" },
  { id: "43", label: "Kabupaten Donggala", value: "Sulawesi Tengah" },
  { id: "44", label: "Kabupaten Ende", value: "Nusa Tenggara Timur" },
  { id: "45", label: "Kabupaten Garut", value: "Jawa Barat" },
  { id: "46", label: "Kabupaten Gayo Lues", value: "Aceh" },
  { id: "47", label: "Kabupaten Gianyar", value: "Bali" },
  { id: "48", label: "Kabupaten Gorontalo", value: "Gorontalo" },
  { id: "49", label: "Kabupaten Gunung Kidul", value: "DI Yogyakarta" },
  { id: "50", label: "Kabupaten Indramayu", value: "Jawa Barat" },
  { id: "51", label: "Kabupaten Intan Jaya", value: "Papua" },
  { id: "52", label: "Kabupaten Jember", value: "Jawa Timur" },
  { id: "53", label: "Kabupaten Jeneponto", value: "Sulawesi Selatan" },
  { id: "54", label: "Kabupaten Jombang", value: "Jawa Timur" },
  { id: "55", label: "Kabupaten Karanganyar", value: "Jawa Tengah" },
  { id: "56", label: "Kabupaten Karawang", value: "Jawa Barat" },
  { id: "57", label: "Kabupaten Karo", value: "Sumatera Utara" },
  { id: "58", label: "Kabupaten Kebumen", value: "Jawa Tengah" },
  { id: "59", label: "Kabupaten Kendal", value: "Jawa Tengah" },
  { id: "60", label: "Kabupaten Klaten", value: "Jawa Tengah" },
  { id: "61", label: "Kabupaten Kubu Raya", value: "Kalimantan Barat" },
  { id: "62", label: "Kabupaten Kupang", value: "Nusa Tenggara Timur" },
  { id: "63", label: "Kabupaten Kutai Barat", value: "Kalimantan Timur" },
  { id: "64", label: "Kabupaten Kutai Kartanegara", value: "Kalimantan Timur" },
  { id: "65", label: "Kabupaten Lamongan", value: "Jawa Timur" },
  { id: "66", label: "Kabupaten Langkat", value: "Sumatera Utara" },
  { id: "67", label: "Kabupaten Lembata", value: "Nusa Tenggara Timur" },
  { id: "68", label: "Kabupaten Luwu", value: "Sulawesi Selatan" },
  { id: "69", label: "Kabupaten Luwu Timur", value: "Sulawesi Selatan" },
  { id: "70", label: "Kabupaten Malang", value: "Jawa Timur" },
  { id: "71", label: "Kabupaten Maluku Tenggara", value: "Maluku" },
  { id: "72", label: "Kabupaten Mandailing Natal", value: "Sumatera Utara" },
  { id: "73", label: "Kabupaten Maros", value: "Sulawesi Selatan" },
  { id: "74", label: "Kabupaten Mataram", value: "Nusa Tenggara Barat" },
  { id: "75", label: "Kabupaten Merangin", value: "Jambi" },
  { id: "76", label: "Kabupaten Muko-Muko", value: "Bengkulu" },
  { id: "77", label: "Kabupaten Nganjuk", value: "Jawa Timur" },
  { id: "78", label: "Kabupaten Ngawi", value: "Jawa Timur" },
  { id: "79", label: "Kabupaten Nias", value: "Sumatera Utara" },
  { id: "80", label: "Kabupaten Nunukan", value: "Kalimantan Utara" },
  { id: "81", label: "Kabupaten Pamekasan", value: "Jawa Timur" },
  { id: "82", label: "Kabupaten Pandeglang", value: "Banten" },
  { id: "83", label: "Kabupaten Pangandaran", value: "Jawa Barat" },
  { id: "84", label: "Kabupaten Pariaman", value: "Sumatera Barat" },
  { id: "85", label: "Kabupaten Pati", value: "Jawa Tengah" },
  { id: "86", label: "Kabupaten Pemalang", value: "Jawa Tengah" },
  {
    id: "87",
    label: "Kabupaten Penukal Abab Lematang Ilir",
    value: "Sumatera Selatan",
  },
  { id: "88", label: "Kabupaten Pesawaran", value: "Lampung" },
  { id: "89", label: "Kabupaten Poso", value: "Sulawesi Tengah" },
  { id: "90", label: "Kabupaten Pringsewu", value: "Lampung" },
  { id: "91", label: "Kabupaten Probolinggo", value: "Jawa Timur" },
  { id: "92", label: "Kabupaten Purworejo", value: "Jawa Tengah" },
  { id: "93", label: "Kabupaten Rembang", value: "Jawa Tengah" },
  { id: "94", label: "Kabupaten Rokan Hilir", value: "Riau" },
  { id: "95", label: "Kabupaten Rokan Hulu", value: "Riau" },
  { id: "96", label: "Kabupaten Sambas", value: "Kalimantan Barat" },
  { id: "97", label: "Kabupaten Sampang", value: "Jawa Timur" },
  { id: "98", label: "Kabupaten Samosir", value: "Sumatera Utara" },
  { id: "99", label: "Kabupaten Sanggau", value: "Kalimantan Barat" },
  { id: "100", label: "Kabupaten Sarolangun", value: "Jambi" },
  { id: "101", label: "Kota Aceh Barat", value: "Aceh" },
  { id: "102", label: "Kota Banda Aceh", value: "Aceh" },
  { id: "103", label: "Kota Medan", value: "Sumatera Utara" },
  { id: "104", label: "Kota Surabaya", value: "Jawa Timur" },
  { id: "105", label: "Kota Jakarta Pusat", value: "DKI Jakarta" },
  { id: "106", label: "Kota Jakarta Barat", value: "DKI Jakarta" },
  { id: "107", label: "Kota Jakarta Selatan", value: "DKI Jakarta" },
  { id: "108", label: "Kota Jakarta Timur", value: "DKI Jakarta" },
  { id: "109", label: "Kota Jakarta Utara", value: "DKI Jakarta" },
  { id: "110", label: "Kota Bandung", value: "Jawa Barat" },
  { id: "111", label: "Kota Semarang", value: "Jawa Tengah" },
  { id: "112", label: "Kota Yogyakarta", value: "DI Yogyakarta" },
  { id: "113", label: "Kota Surakarta", value: "Jawa Tengah" },
  { id: "114", label: "Kota Malang", value: "Jawa Timur" },
  { id: "115", label: "Kota Makassar", value: "Sulawesi Selatan" },
  { id: "116", label: "Kota Medan", value: "Sumatera Utara" },
  { id: "117", label: "Kota Balikpapan", value: "Kalimantan Timur" },
  { id: "118", label: "Kota Banjarmasin", value: "Kalimantan Selatan" },
  { id: "119", label: "Kota Batam", value: "Kepulauan Riau" },
  { id: "120", label: "Kota Denpasar", value: "Bali" },
  { id: "121", label: "Kota Palembang", value: "Sumatera Selatan" },
  { id: "122", label: "Kota Pontianak", value: "Kalimantan Barat" },
  { id: "123", label: "Kota Samarinda", value: "Kalimantan Timur" },
  { id: "124", label: "Kota Pekanbaru", value: "Riau" },
  { id: "125", label: "Kota Surakarta", value: "Jawa Tengah" },
  { id: "126", label: "Kota Bogor", value: "Jawa Barat" },
  { id: "127", label: "Kota Tangerang", value: "Banten" },
  { id: "128", label: "Kota Depok", value: "Jawa Barat" },
  { id: "129", label: "Kota Bekasi", value: "Jawa Barat" },
  { id: "130", label: "Kota Batam", value: "Kepulauan Riau" },
  { id: "131", label: "Kota Ambon", value: "Maluku" },
  { id: "132", label: "Kota Palu", value: "Sulawesi Tengah" },
  { id: "133", label: "Kota Kendari", value: "Sulawesi Tenggara" },
  { id: "134", label: "Kota Mataram", value: "Nusa Tenggara Barat" },
  { id: "135", label: "Kota Kupang", value: "Nusa Tenggara Timur" },
];
